### ISSUE TITLE
potential missing bit?

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/cd-dice-roller#4]
how do we get from the `rollButton()` code in step 3 to the code at the end of step 4?

I'm not sure whether I just didn't follow correctly, or whether there is something missing there.

**Comment by daraghbroderick** [comment]
Hey, I'm after looking at this again and can't spot anything absent ( very possibly due to looking at it for so long). The only difference in the code between the steps, is the addition of the for loop in step 4 and the line 'var numberOfDice = getNumDice();' The code inside the for loop is code that the learner should already have used. Is there something more specific you spotted that is causing confusion?

**Comment by JaninaPi** [comment]
The thing that's confusing me is step 4, line 80:
`var numberOfDice = getNumDice();`

I think line 71 implies that this variable should be created, but then line 75 just says to move the existing code, so it's a bit vague maybe?

**Comment by daraghbroderick** [comment]
Found the missing bit, great spot! I've added a small instruction to add that line before the for loop on line 71.
`Your for loop has to run once for each die roll. This means you need the number chosen in the select drop-down menu. The function getNumDice() gives you that number, add the line var numberOfDice = getNumDice(); just before your for loop.`

**Comment by JaninaPi** [comment]
cheers!
